config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'home#index'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :photo, :address)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  	@destinations = Destination.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destinations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Photo</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.name %></td>
        <td><%= destination.photo %></td>
        <td><%= destination.address %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination.name %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @destination.photo %>
</p>

<p>
  <strong>Address:</strong>
  <%= @destination.address %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
 <!-- googlemapsapi key AIzaSyDX5XmleXXlKzL-iSTX85n3qbZYasucmnk -->

<div id="map-canvas"></div>

  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDX5XmleXXlKzL-iSTX85n3qbZYasucmnk">
 </script>

 <script>
 	$(document).ready(function (){
    function initialize(){
	 var myLatlng = new google.maps.LatLng(32.7812034, -96.8064713);
      var mapOptions = {
      center: myLatlng,
      zoom: 5
      };

      var map = new google.maps.Map(document.getElementById('map-canvas'),
                mapOptions);

      var items = []

      <% @destinations.each do |destination| %>
        items.push({
          name: '<%= destination.name %>',
          latitude: '<%= destination.latitude %>',
          longitude: '<%= destination.longitude %>',
          photo: '<%= destination.photo %>'
          
        });
      <% end %>

        items.forEach(function(item) {

        var markerLatLng = new google.maps.LatLng(item.latitude, item.longitude);

        var marker = item.id = new google.maps.Marker({
          position: markerLatLng,
          map: map,
          name: item.name,
          animation: google.maps.Animation.DROP,
          draggable: true
        });

        var contentString = '<h2>' + item.name + '</h2> '
          + '<img class="marker" src="' + item.photo + '">';

        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

	 google.maps.event.addListener(marker, 'click', function() {
	    infowindow.open(map,marker);
	 });  		  
});
    }


    google.maps.event.addDomListener(window, 'load', initialize);
});



 </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GooglemapsAPI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>



</body>
</html>